/* =========================================
   VIP KIBRIS TRAVEL - DİL SÖZLÜĞÜ (lang.js)
========================================= */

const translations = {
    tr: {
        // --- ORTAK (MENÜ & FOOTER) ---
        topbar_service: "7/24 Hizmetinizdeyiz",
        topbar_whatsapp: "WhatsApp Destek",
        nav_home: "ANA SAYFA",
        nav_about: "HAKKIMIZDA",
        nav_services: "HİZMETLERİMİZ",
        nav_vehicles: "ARAÇLARIMIZ",
        nav_tours: "TURLAR",
        nav_contact: "İLETİŞİM",
        footer_desc: "KKTC geneline VIP transfer ve turizm hizmeti. Güvenli ve konforlu ulaşım.",
        footer_menu_title: "HIZLI MENÜ",
        footer_contact_title: "İLETİŞİM",
        footer_copyright: "Tüm Hakları Saklıdır.",

        // --- ANA SAYFA (INDEX) ---
        hero_title_1: "Lüks ve Konforun Adresi",
        hero_desc_1: "Mercedes Vito araçlarımızla Ercan Havalimanı transferleri ve özel Kıbrıs turları.",
        hero_title_2: "Tatil Yolculuğunuz Başlasın",
        hero_desc_2: "Ercan'dan otelinize zamanında, güvenli ve konforlu VIP ulaşım.",
        form_pickup: "Alınış Noktası (Örn: Ercan Havalimanı)",
        form_dropoff: "Bırakılış Noktası (Örn: Girne Otel)",
        form_btn_price: "FİYAT SOR",

        sec_services_sub: "HİZMETLERİMİZ",
        sec_services_title: "Siz Değerli Misafirlerimize Sunduğumuz Çözümler",
        srv_1_title: "Otel Transfer",
        srv_1_desc: "Ercan havalimanı otel transferi ihtiyaçlarınız için VIP çözümler sunuyoruz.",
        srv_2_title: "Şoförlü Araç Tahsisi",
        srv_2_desc: "Özel şoförlü araç kiralama hizmetlerimiz ile konforlu bir yolculuğa adım atın.",
        srv_3_title: "VIP Karşılama",
        srv_3_desc: "Misafirleriniz havalimanında isimle karşılanıp Lux araçlarına kadar eşlik edilir.",
        srv_4_title: "Gece Turları",
        srv_4_desc: "Kıbrıs'ın eğlence hayatına VIP araçlarımız ve özel şoförlerimizle katılın.",

        sec_testi_sub: "MÜŞTERİ YORUMLARI",
        sec_testi_title: "SİZDEN GELEN YORUMLAR",
        testi_1_desc: "Mükemmel hizmet güler yüzlü personel, havalimanından otele kadar çok rahat ettik.",
        testi_2_desc: "Ekstra konfor ve zamanlama harikaydı. Kıbrıs'ta tek geçerim, kesinlikle öneriyorum.",
        testi_3_desc: "Araçlar pırıl pırıl. Ailemle yaptığım tatilin en rahat kısmı transferimizdi.",

        sec_offer_sub: "HEMEN TEKLİF AL",
        sec_offer_title: "Özel anlar, güzel birliktelikler.",
        sec_offer_desc: "En uygun fiyatlı VIP transfer teklifleri için formumuzu doldurun.",
        offer_box_title: "BİZDEN TEKLİF ALMADAN PLAN YAPMAYIN",
        offer_box_discount: "GİDİŞ-DÖNÜŞ REZERVASYONU %10 İNDİRİMLİ!",
        form_name: "Ad-Soyad",
        form_email: "E-Mail",
        form_phone: "Telefon",
        form_passengers: "Yolcu Sayısı",
        form_message: "Mesajınız",
        form_btn_offer: "TEKLİF AL",

        sec_tours_sub: "TURLAR",
        sec_tours_title: "Kıbrıs'ın Tarihi ve Doğal Güzelliklerini Keşfedin",
        tour_1_badge: "TARİHİ GİRNE",
        tour_1_title: "GİRNE TURU",
        tour_1_desc: "Girne Kalesi, Bellapais Manastırı ve Eski Liman'ın eşsiz atmosferi.",
        tour_2_badge: "ANTİK SALAMİS",
        tour_2_title: "MAGOSA TURU",
        tour_2_desc: "Salamis Antik Kenti ve Kapalı Maraş'ın gizemli tarihine tanıklık edin.",
        tour_3_badge: "BAŞKENT KÜLTÜR",
        tour_3_title: "LEFKOŞA TURU",
        tour_3_desc: "Büyük Han ve Selimiye Camii rotasıyla başkentin kültürel dokusunu yaşayın.",
        tour_4_badge: "MAVİ KÖŞK",
        tour_4_title: "GÜZELYURT TURU",
        tour_4_desc: "Mavi Köşk, St. Mamas Manastırı ve Soli Antik Kenti keşfi.",

        sec_vehicles_sub: "ARAÇLARIMIZ",
        sec_vehicles_title: "SİZİN İHTİYAÇLARINIZ İÇİN HAZIRIZ",
        veh_1_badge: "VİP ARAÇ",
        veh_1_title: "MERCEDES VİTO",
        veh_1_desc: "Deneyimli şoförlerimizle konforu en üst seviyede yaşayın.",
        veh_2_badge: "VİP MİNİBÜS",
        veh_2_title: "VİP SPRİNTER",
        veh_2_desc: "Geniş gruplar için ideal, donanımlı ve lüks araç çözümü.",
        veh_3_badge: "MAYBACH",
        veh_3_title: "MAYBACH VİTO",
        veh_3_desc: "Özel misafirleriniz için tamamen VIP tasarlanmış eşsiz bir araç.",

        // --- ARAÇLARIMIZ SAYFASI ---
        veh_page_title: "LÜKS ARAÇ FİLOMUZ",
        veh_page_h1: "VIP Araçlarımız",
        veh_page_sub: "KONFORUNUZ İÇİN",
        veh_page_h2: "Geniş ve Modern Araç Filomuz",
        veh1_tag: "MERCEDES MARKA",
        veh1_title: "MERCEDES VITO VIP (6+1)",
        veh1_desc: "Kıbrıs tatilinizde aileniz veya arkadaş grubunuz için en konforlu seçenek. Geniş bagaj hacmi ve deri koltuk tasarımıyla prestiji hissedin.",
        veh1_spec_pax: "6+1 Kişi",
        veh1_spec_lug: "5 Bagaj",
        veh1_spec_ac: "Klima",
        veh2_tag: "MERCEDES MARKA",
        veh2_title: "MERCEDES SPRINTER VIP (15+1)",
        veh2_desc: "Geniş gruplar, düğün organizasyonları ve casino turları için ideal, yüksek tavanlı ve TV üniteli VIP minibüsümüz.",
        veh2_spec_pax: "15+1 Kişi",
        veh2_spec_lug: "15 Bagaj",
        veh2_spec_tv: "Eğlence Paketi",
        tab_rez: "REZERVASYON YAP",
        tab_gal: "ARAÇ RESİMLERİ",
        tab_com: "MÜŞTERİ YORUMLARI",
        pl_name: "Ad Soyad",
        pl_phone: "Telefon",
        btn_offer: "TEKLİF AL",
        com1_text: "\"Araç çok temizdi, şoför bey bizi kapıda karşıladı. Teşekkürler.\" - Ahmet Y.",
        com2_text: "\"Grup olarak çok memnun kaldık, araç içi ikramlar harikaydı.\" - Mehmet K.",

        // --- HAKKIMIZDA SAYFASI ---
        about_page_title: "VIP KIBRIS TRAVEL",
        about_page_h1: "Hakkımızda",
        about_sub: "BİZ KİMİZ?",
        about_h2: "Kıbrıs'ta Yolculuğu Sanata Dönüştürüyoruz",
        about_p1: "<strong>VIP KIBRIS TRAVEL</strong> olarak, Kuzey Kıbrıs Türk Cumhuriyeti'nde (KKTC) uzun yıllardır turizm, ulaşım ve VIP transfer sektöründe öncü bir rol üstlenmekteyiz. Amacımız, adaya ayak bastığınız ilk andan itibaren size sadece bir transfer hizmeti değil, prestijli bir yaşam tarzı sunmaktır.",
        about_p2: "Ercan Havalimanı transferleri ve özel turlarımızla; bireysel misafirlerimizden kurumsal şirket yöneticilerine kadar geniş bir yelpazede hizmet sunuyoruz. Filomuzda bulunan lüks Mercedes araçlarımız ve alanında uzman ekibimizle 7 gün 24 saat kesintisiz hizmet sağlıyoruz.",
        about_miss_title: "Misyonumuz",
        about_miss_desc: "Güvenliği ve kaliteyi en ön planda tutarak, ulaşım sektöründe fark yaratan, misafir memnuniyeti odaklı hizmetler sunmak.",
        about_vis_title: "Vizyonumuz",
        about_vis_desc: "Kuzey Kıbrıs'ın turizm ve transfer sektöründe akla gelen ilk, en yenilikçi ve en güvenilir VIP markası olmak.",
        about_cert_title: "Resmi Onaylı Acente",
        about_cert_desc: "Firmamız TÜRSAB ve KKTC Turizm Bakanlığı tarafından yetkilendirilmiş profesyonel bir seyahat acentesidir.",
        about_cert_btn: "SİTEYİ DOĞRULA",
        about_help_title: "Yardıma mı ihtiyacınız var?",
        about_help_desc: "7/24 Operasyon ekibimiz sorularınızı yanıtlamaya hazır.",
        about_help_btn: "Hemen Ara",
        about_trust_tag: "GÜVEN VE KALİTE",
        about_trust_title: "Kalitemizi Belgeliyoruz",
        about_trust_desc: "Tüm araçlarımız yolcu taşımacılığı belgelerine ve KKTC yüksek güvenlik standartlarına sahiptir.",
        about_exp_year: "Yıllık Tecrübe",

        // --- HİZMETLERİMİZ SAYFASI ---
        srv_page_tag: "VIP AYRICALIĞI",
        srv_page_title: "Hizmetlerimizde Sınır Tanımıyoruz",
        srv_page_1_badge: "VIP TRANSFER",
        srv_page_1_title: "Ercan Havalimanı VIP Transfer",
        srv_page_1_p1: "Kıbrıs'a adım attığınız ilk andan itibaren ayrıcalıklı olduğunuzu hissedin. Ercan Havalimanı'ndan Girne, Lefkoşa, Magosa veya Bafra bölgesindeki otelinize lüks Mercedes Vito araçlarımızla kesintisiz ve konforlu bir şekilde ulaştırıyoruz.",
        srv_page_1_p2: "Günün her saati (7/24) önceden rezervasyon yaparak uçak rötar dertlerini düşünmeden güvenle seyahat edebilirsiniz. Şoförünüz sizi isminizle karşılar.",
        srv_page_1_btn: "TEKLİF AL",
        srv_page_2_badge: "ÖZEL TAHSİS",
        srv_page_2_title: "Şoförlü Araç Tahsisi",
        srv_page_2_p1: "İş toplantılarınız, özel davetleriniz veya gün boyu sürecek ada içi ziyaretleriniz için profesyonel şoförlü VIP araç kiralama hizmeti sunuyoruz. Sadece rotanızı belirleyin, gerisini bize bırakın.",
        srv_page_2_p2: "Tam donanımlı, Wi-Fi erişimli ve ikramlı araçlarımızla şoförümüz sizi dilediğiniz yerde beklesin. Zaman yönetimi tamamen sizin elinizde.",
        srv_page_2_btn: "DETAYLI BİLGİ",
        srv_page_3_badge: "KARŞILAMA",
        srv_page_3_title: "VIP Karşılama ve Asistanlık",
        srv_page_3_p1: "Özel misafirlerinizi veya şirket yetkililerinizi sizin adınıza en prestijli şekilde karşılıyoruz. İsim veya şirket logolu özel tabelalarla karşılama yapıyor, bagaj asistanlığı sağlıyoruz.",
        srv_page_3_p2: "İlk intibanın ne kadar önemli olduğunu biliyoruz. Misafirlerinize kendilerini özel hissettirecek kusursuz bir operasyon yürütüyoruz.",
        srv_page_3_btn: "REZERVASYON",
        // --- TURLAR SAYFASI ---
        tour_page_tag: "KIBRIS'I KEŞFEDİN",
        tour_page_h1: "Özel Kıbrıs Turları",
        tour_page_p: "Lüks araçlarımızla adanın binlerce yıllık tarihini konforla keşfedin.",
        tour_page_sub: "POPÜLER ROTALAR",
        tour_page_h2: "Kıbrıs Kültür ve Doğa Turları",

        t1_badge: "VIP Tur",
        t1_tag: "Girne Bölgesi",
        t1_title: "Girne & Bellapais",
        t1_desc: "Limanın büyüleyici atmosferi ve Bellapais Manastırı'nın eşsiz mimarisi.",
        t1_l1: "Girne Kalesi",
        t1_l2: "Eski Yat Limanı",
        t1_l3: "Bellapais Manastırı",

        t2_badge: "En Çok Tercih Edilen",
        t2_tag: "Magosa Bölgesi",
        t2_title: "Magosa & Maraş",
        t2_desc: "Antik Salamis harabeleri ve kapalı Maraş'ın gizemli tarihine tanıklık edin.",
        t2_l1: "Salamis Antik Kenti",
        t2_l2: "Lala Mustafa Paşa",
        t2_l3: "Kapalı Maraş",

        t3_badge: "Başkent",
        t3_tag: "Başkent",
        t3_title: "Lefkoşa Kültür",
        t3_desc: "Dünyanın bölünmüş tek başkentinde Osmanlı ve Lüzinyan izlerini sürün.",
        t3_l1: "Büyük Han",
        t3_l2: "Selimiye Camii",
        t3_l3: "Arasta Çarşısı",

        t4_badge: "Doğa",
        t4_tag: "Karpaz Bölgesi",
        t4_title: "Karpaz & Altınkum",
        t4_desc: "Adanın en bakir doğası, hür eşekleri ve muhteşem Altınkum plajı.",
        t4_l1: "Apostolos Andreas",
        t4_l2: "Altın Kum Plajı",
        t4_l3: "Dipkarpaz Köyü",

        tab_places: "YERLER",
        tab_gallery: "GALERİ",
        btn_tour_offer: "TEKLİF AL",
        // --- İLETİŞİM SAYFASI ---
        contact_page_tag: "BİZE ULAŞIN",
        contact_page_h1: "İletişim",
        contact_page_p: "Sorularınız, rezervasyon talepleriniz ve özel turlarınız için bize 7/24 ulaşabilirsiniz.",

        contact_address_title: "Adresimiz",
        contact_address_desc: "Girne Limanı Mevkii, No:45 <br> Girne / KKTC",
        contact_phone_title: "Telefon & WhatsApp",
        contact_email_title: "E-Posta",

        contact_form_title: "Mesaj Gönderin",
        contact_label_name: "Adınız Soyadınız",
        contact_ph_name: "Örn: Ahmet Yılmaz",
        contact_label_phone: "Telefon Numaranız",
        contact_ph_phone: "05XX XXX XX XX",
        contact_label_email: "E-Posta Adresiniz",
        contact_ph_email: "ornek@mail.com",
        contact_label_subject: "Konu",
        contact_opt_1: "Transfer Rezervasyonu",
        contact_opt_2: "Tur Bilgisi",
        contact_opt_3: "Şikayet / Öneri",
        contact_opt_4: "Diğer",
        contact_label_message: "Mesajınız",
        contact_ph_message: "Size nasıl yardımcı olabiliriz?",
        contact_btn_send: "MESAJI GÖNDER",
        //WP MESSAGE
        wp_msg_default: "Merhaba, VIP Transfer hizmetleriniz hakkında bilgi almak istiyorum.",
        wp_msg_srv1: "Merhaba, Otel Transfer hizmetiniz hakkında bilgi alabilir miyim?",
        wp_msg_srv2: "Merhaba, Şoförlü Araç Tahsisi hakkında bilgi alabilir miyim?",
        wp_msg_srv3: "Merhaba, VIP Karşılama hizmetiniz hakkında bilgi alabilir miyim?",
        wp_msg_tour_girne: "Merhaba, Girne & Bellapais turu hakkında bilgi ve fiyat alabilir miyim?",
        wp_msg_tour_magosa: "Merhaba, Magosa & Maraş turu hakkında bilgi ve fiyat alabilir miyim?",
    },
    en: {
        topbar_service: "24/7 At Your Service",
        topbar_whatsapp: "WhatsApp Support",
        nav_home: "HOME",
        nav_about: "ABOUT US",
        nav_services: "SERVICES",
        nav_vehicles: "OUR FLEET",
        nav_tours: "TOURS",
        nav_contact: "CONTACT",
        footer_desc: "VIP transfer and tourism services throughout the TRNC. Safe and comfortable transportation.",
        footer_menu_title: "QUICK MENU",
        footer_contact_title: "CONTACT",
        footer_copyright: "All Rights Reserved.",

        hero_title_1: "Address of Luxury and Comfort",
        hero_desc_1: "Ercan Airport transfers and private Cyprus tours with our Mercedes Vito vehicles.",
        hero_title_2: "Let Your Holiday Journey Begin",
        hero_desc_2: "On-time, safe, and comfortable VIP transportation from Ercan to your hotel.",
        form_pickup: "Pick-up Location (e.g., Ercan Airport)",
        form_dropoff: "Drop-off Location (e.g., Kyrenia Hotel)",
        form_btn_price: "GET A QUOTE",

        sec_services_sub: "OUR SERVICES",
        sec_services_title: "Solutions We Offer to Our Valued Guests",
        srv_1_title: "Hotel Transfer",
        srv_1_desc: "We offer VIP solutions for your Ercan airport hotel transfer needs.",
        srv_2_title: "Chauffeured Vehicle Allocation",
        srv_2_desc: "Step into a comfortable journey with our private chauffeured car rental services.",
        srv_3_title: "VIP Meet & Greet",
        srv_3_desc: "Your guests are greeted by name at the airport and accompanied to their Lux vehicles.",
        srv_4_title: "Night Tours",
        srv_4_desc: "Join Cyprus nightlife with our VIP vehicles and private chauffeurs.",

        sec_testi_sub: "CUSTOMER REVIEWS",
        sec_testi_title: "FEEDBACK FROM YOU",
        testi_1_desc: "Excellent service, smiling staff, we were very comfortable from the airport to the hotel.",
        testi_2_desc: "Extra comfort and timing was great. The best in Cyprus, definitely recommend.",
        testi_3_desc: "Vehicles are sparkling clean. The transfer was the most comfortable part of our family vacation.",

        sec_offer_sub: "GET A QUOTE NOW",
        sec_offer_title: "Special moments, beautiful gatherings.",
        sec_offer_desc: "Fill out our form for the most affordable VIP transfer quotes.",
        offer_box_title: "DO NOT PLAN WITHOUT GETTING A QUOTE FROM US",
        offer_box_discount: "10% DISCOUNT ON ROUND-TRIP RESERVATIONS!",
        form_name: "Full Name",
        form_email: "E-Mail",
        form_phone: "Phone",
        form_passengers: "Passengers",
        form_message: "Your Message",
        form_btn_offer: "GET QUOTE",

        sec_tours_sub: "TOURS",
        sec_tours_title: "Discover the Historical and Natural Beauties of Cyprus",
        tour_1_badge: "HISTORIC KYRENIA",
        tour_1_title: "KYRENIA TOUR",
        tour_1_desc: "The unique atmosphere of Kyrenia Castle, Bellapais Monastery, and the Old Harbour.",
        tour_2_badge: "ANTIQUE SALAMIS",
        tour_2_title: "FAMAGUSTA TOUR",
        tour_2_desc: "Witness the mysterious history of the Ancient City of Salamis and Varosha.",
        tour_3_badge: "CAPITAL CULTURE",
        tour_3_title: "NICOSIA TOUR",
        tour_3_desc: "Experience the cultural texture of the capital with the Great Inn and Selimiye Mosque route.",
        tour_4_badge: "BLUE HOUSE",
        tour_4_title: "MORPHOU TOUR",
        tour_4_desc: "Discovery of the Blue House, St. Mamas Monastery, and the Ancient City of Soli.",

        sec_vehicles_sub: "OUR FLEET",
        sec_vehicles_title: "WE ARE READY FOR YOUR NEEDS",
        veh_1_badge: "VIP VEHICLE",
        veh_1_title: "MERCEDES VITO",
        veh_1_desc: "Experience comfort at the highest level with our experienced chauffeurs.",
        veh_2_badge: "VIP MINIBUS",
        veh_2_title: "VIP SPRINTER",
        veh_2_desc: "Ideal for large groups, equipped and luxurious vehicle solution.",
        veh_3_badge: "MAYBACH",
        veh_3_title: "MAYBACH VITO",
        veh_3_desc: "A unique, fully VIP-designed vehicle for your special guests.",

        veh_page_title: "OUR LUXURY FLEET",
        veh_page_h1: "Our VIP Vehicles",
        veh_page_sub: "FOR YOUR COMFORT",
        veh_page_h2: "Our Large and Modern Fleet",
        veh1_tag: "MERCEDES BRAND",
        veh1_title: "MERCEDES VITO VIP (6+1)",
        veh1_desc: "The most comfortable option for your family or group of friends during your Cyprus holiday. Feel the prestige with its large luggage capacity and leather seat design.",
        veh1_spec_pax: "6+1 Pax",
        veh1_spec_lug: "5 Luggage",
        veh1_spec_ac: "A/C",
        veh2_tag: "MERCEDES BRAND",
        veh2_title: "MERCEDES SPRINTER VIP (15+1)",
        veh2_desc: "Our VIP minibus with high ceiling and TV unit, ideal for large groups, wedding organizations, and casino tours.",
        veh2_spec_pax: "15+1 Pax",
        veh2_spec_lug: "15 Luggage",
        veh2_spec_tv: "Entertainment",
        tab_rez: "MAKE RESERVATION",
        tab_gal: "VEHICLE IMAGES",
        tab_com: "CUSTOMER REVIEWS",
        pl_name: "Full Name",
        pl_phone: "Phone",
        btn_offer: "GET QUOTE",
        com1_text: "\"The vehicle was very clean, the driver greeted us at the door. Thank you.\" - Ahmet Y.",
        com2_text: "\"As a group, we were very pleased, the in-car treats were wonderful.\" - Mehmet K.",

        about_page_title: "VIP CYPRUS TRAVEL",
        about_page_h1: "About Us",
        about_sub: "WHO ARE WE?",
        about_h2: "We Transform Journey into Art in Cyprus",
        about_p1: "As <strong>VIP CYPRUS TRAVEL</strong>, we have been taking a leading role in the tourism, transportation, and VIP transfer sector in the Turkish Republic of Northern Cyprus (TRNC) for many years. Our goal is to offer you not just a transfer service, but a prestigious lifestyle from the very first moment you step on the island.",
        about_p2: "With our Ercan Airport transfers and private tours; we offer a wide range of services from individual guests to corporate company executives. We provide uninterrupted 24/7 service with our luxury Mercedes vehicles in our fleet and our expert team.",
        about_miss_title: "Our Mission",
        about_miss_desc: "To provide guest satisfaction-oriented services that make a difference in the transportation sector by prioritizing safety and quality.",
        about_vis_title: "Our Vision",
        about_vis_desc: "To be the first, most innovative, and most reliable VIP brand that comes to mind in the tourism and transfer sector of Northern Cyprus.",
        about_cert_title: "Officially Approved Agency",
        about_cert_desc: "Our company is a professional travel agency authorized by TÜRSAB and the TRNC Ministry of Tourism.",
        about_cert_btn: "VERIFY SITE",
        about_help_title: "Need help?",
        about_help_desc: "Our 24/7 Operations team is ready to answer your questions.",
        about_help_btn: "Call Now",
        about_trust_tag: "TRUST AND QUALITY",
        about_trust_title: "We Certify Our Quality",
        about_trust_desc: "All our vehicles have passenger transport certificates and TRNC high security standards.",
        about_exp_year: "Years of Experience",

        // --- SERVICES PAGE ---
        srv_page_tag: "VIP PRIVILEGE",
        srv_page_title: "We Know No Limits in Our Services",
        srv_page_1_badge: "VIP TRANSFER",
        srv_page_1_title: "Ercan Airport VIP Transfer",
        srv_page_1_p1: "Feel privileged from the first moment you step into Cyprus. We transfer you from Ercan Airport to your hotel in Kyrenia, Nicosia, Famagusta or Bafra regions uninterruptedly and comfortably with our luxury Mercedes Vito vehicles.",
        srv_page_1_p2: "You can travel safely by making a reservation in advance at any time of the day (24/7) without worrying about flight delays. Your driver will greet you by your name.",
        srv_page_1_btn: "GET QUOTE",
        srv_page_2_badge: "PRIVATE ALLOCATION",
        srv_page_2_title: "Chauffeured Vehicle Allocation",
        srv_page_2_p1: "We offer professional chauffeured VIP car rental services for your business meetings, private invitations or all-day island visits. Just set your route and leave the rest to us.",
        srv_page_2_p2: "Let our driver wait for you wherever you want with our fully equipped, Wi-Fi accessible vehicles with refreshments. Time management is entirely in your hands.",
        srv_page_2_btn: "DETAILS",
        srv_page_3_badge: "MEET & GREET",
        srv_page_3_title: "VIP Meet and Greet Assistance",
        srv_page_3_p1: "We welcome your special guests or company officials on your behalf in the most prestigious way. We welcome with special signs with names or company logos and provide luggage assistance.",
        srv_page_3_p2: "We know how important the first impression is. We carry out a flawless operation that will make your guests feel special.",
        srv_page_3_btn: "RESERVATION",
        // --- TOURS PAGE ---
        tour_page_tag: "DISCOVER CYPRUS",
        tour_page_h1: "Private Cyprus Tours",
        tour_page_p: "Discover the island's thousands of years of history in comfort with our luxury vehicles.",
        tour_page_sub: "POPULAR ROUTES",
        tour_page_h2: "Cyprus Culture and Nature Tours",

        t1_badge: "VIP Tour",
        t1_tag: "Kyrenia Region",
        t1_title: "Kyrenia & Bellapais",
        t1_desc: "The fascinating atmosphere of the harbor and the unique architecture of Bellapais Monastery.",
        t1_l1: "Kyrenia Castle",
        t1_l2: "Old Marina",
        t1_l3: "Bellapais Monastery",

        t2_badge: "Most Preferred",
        t2_tag: "Famagusta Region",
        t2_title: "Famagusta & Varosha",
        t2_desc: "Witness the ancient Salamis ruins and the mysterious history of closed Varosha.",
        t2_l1: "Salamis Ancient City",
        t2_l2: "Lala Mustafa Pasha",
        t2_l3: "Closed Varosha",

        t3_badge: "Capital",
        t3_tag: "Capital",
        t3_title: "Nicosia Culture",
        t3_desc: "Trace the Ottoman and Lusignan footprints in the world's only divided capital.",
        t3_l1: "Great Inn (Büyük Han)",
        t3_l2: "Selimiye Mosque",
        t3_l3: "Arasta Bazaar",

        t4_badge: "Nature",
        t4_tag: "Karpaz Region",
        t4_title: "Karpaz & Golden Beach",
        t4_desc: "The most virgin nature of the island, free donkeys and the magnificent Golden Beach.",
        t4_l1: "Apostolos Andreas",
        t4_l2: "Golden Beach",
        t4_l3: "Dipkarpaz Village",

        tab_places: "PLACES",
        tab_gallery: "GALLERY",
        btn_tour_offer: "GET QUOTE",
        // --- CONTACT PAGE ---
        contact_page_tag: "CONTACT US",
        contact_page_h1: "Contact",
        contact_page_p: "You can reach us 24/7 for your questions, reservation requests and private tours.",

        contact_address_title: "Our Address",
        contact_address_desc: "Kyrenia Harbour Area, No:45 <br> Kyrenia / TRNC",
        contact_phone_title: "Phone & WhatsApp",
        contact_email_title: "E-Mail",

        contact_form_title: "Send a Message",
        contact_label_name: "Full Name",
        contact_ph_name: "e.g., John Doe",
        contact_label_phone: "Phone Number",
        contact_ph_phone: "+90 5XX XXX XX XX",
        contact_label_email: "E-Mail Address",
        contact_ph_email: "example@mail.com",
        contact_label_subject: "Subject",
        contact_opt_1: "Transfer Reservation",
        contact_opt_2: "Tour Information",
        contact_opt_3: "Complaint / Suggestion",
        contact_opt_4: "Other",
        contact_label_message: "Your Message",
        contact_ph_message: "How can we help you?",
        contact_btn_send: "SEND MESSAGE",
        //WP MESSAGE
        wp_msg_default: "Hello, I would like to get information about your VIP Transfer services.",
        wp_msg_srv1: "Hello, could I get information about your Hotel Transfer service?",
        wp_msg_srv2: "Hello, could I get information about Chauffeured Vehicle Allocation?",
        wp_msg_srv3: "Hello, could I get information about your VIP Meet & Greet service?",
        wp_msg_tour_girne: "Hello, I would like to get information and pricing for the Kyrenia & Bellapais tour.",
        wp_msg_tour_magosa: "Hello, I would like to get information and pricing for the Famagusta & Varosha tour.",
    },
    ru: {
        topbar_service: "К Вашим Услугам 24/7",
        topbar_whatsapp: "Поддержка WhatsApp",
        nav_home: "ГЛАВНАЯ",
        nav_about: "О НАС",
        nav_services: "УСЛУГИ",
        nav_vehicles: "АВТОПАРК",
        nav_tours: "ТУРЫ",
        nav_contact: "КОНТАКТЫ",
        footer_desc: "Услуги VIP-трансфера и туризма по всему ТРСК. Безопасные и комфортные перевозки.",
        footer_menu_title: "БЫСТРОЕ МЕНЮ",
        footer_contact_title: "КОНТАКТЫ",
        footer_copyright: "Все права защищены.",

        hero_title_1: "Адрес Роскоши и Комфорта",
        hero_desc_1: "Трансферы из аэропорта Эрджан и частные туры по Кипру на наших Mercedes Vito.",
        hero_title_2: "Пусть Начнется Ваше Путешествие",
        hero_desc_2: "Своевременный, безопасный и комфортный VIP-трансфер из Эрджана в ваш отель.",
        form_pickup: "Место отправления (напр., Аэропорт Эрджан)",
        form_dropoff: "Место назначения (напр., Отель Кирения)",
        form_btn_price: "УЗНАТЬ ЦЕНУ",

        sec_services_sub: "НАШИ УСЛУГИ",
        sec_services_title: "Решения, которые мы предлагаем нашим дорогим гостям",
        srv_1_title: "Трансфер в отель",
        srv_1_desc: "Мы предлагаем VIP-решения для ваших трансферов из аэропорта Эрджан.",
        srv_2_title: "Аренда авто с водителем",
        srv_2_desc: "Шагните в комфортное путешествие с нашими услугами по аренде автомобилей.",
        srv_3_title: "VIP Встреча",
        srv_3_desc: "Ваших гостей встретят по имени в аэропорту и проводят к их Lux автомобилям.",
        srv_4_title: "Ночные туры",
        srv_4_desc: "Присоединяйтесь к ночной жизни Кипра с нашими VIP-автомобилями.",

        sec_testi_sub: "ОТЗЫВЫ КЛИЕНТОВ",
        sec_testi_title: "ОТЗЫВЫ ОТ ВАС",
        testi_1_desc: "Отличный сервис, улыбчивый персонал, нам было очень комфортно от аэропорта до отеля.",
        testi_2_desc: "Дополнительный комфорт и время были великолепны. Лучшие на Кипре, определенно рекомендую.",
        testi_3_desc: "Машины сверкают чистотой. Трансфер был самой комфортной частью нашего отдыха.",

        sec_offer_sub: "ПОЛУЧИТЬ ЦЕНУ СЕЙЧАС",
        sec_offer_title: "Особые моменты, прекрасные встречи.",
        sec_offer_desc: "Заполните форму для получения самых выгодных предложений на VIP-трансфер.",
        offer_box_title: "НЕ ПЛАНИРУЙТЕ БЕЗ НАШЕГО ПРЕДЛОЖЕНИЯ",
        offer_box_discount: "СКИДКА 10% НА БРОНИРОВАНИЕ ТУДА-ОБРАТНО!",
        form_name: "Имя-Фамилия",
        form_email: "Эл. адрес",
        form_phone: "Телефон",
        form_passengers: "Пассажиры",
        form_message: "Ваше сообщение",
        form_btn_offer: "ПОЛУЧИТЬ ЦЕНУ",

        sec_tours_sub: "ТУРЫ",
        sec_tours_title: "Откройте для себя исторические и природные красоты Кипра",
        tour_1_badge: "ИСТОРИЧЕСКАЯ КИРЕНИЯ",
        tour_1_title: "ТУР ПО КИРЕНИИ",
        tour_1_desc: "Уникальная атмосфера Киренийского замка, аббатства Беллапаис и Старой гавани.",
        tour_2_badge: "АНТИЧНЫЙ САЛАМИН",
        tour_2_title: "ТУР В ФАМАГУСТУ",
        tour_2_desc: "Станьте свидетелем загадочной истории древнего города Саламин и Вароши.",
        tour_3_badge: "КУЛЬТУРА СТОЛИЦЫ",
        tour_3_title: "ТУР ПО НИКОСИИ",
        tour_3_desc: "Окунитесь в культурную атмосферу столицы по маршруту Бюйюк-Хан и мечети Селимие.",
        tour_4_badge: "СИНИЙ ДОМ",
        tour_4_title: "ТУР В МОРФУ",
        tour_4_desc: "Знакомство с Голубым домом, монастырем Св. Мамаса и древним городом Соли.",

        sec_vehicles_sub: "НАШ АВТОПАРК",
        sec_vehicles_title: "МЫ ГОТОВЫ К ВАШИМ ПОТРЕБНОСТЯМ",
        veh_1_badge: "VIP АВТО",
        veh_1_title: "MERCEDES VITO",
        veh_1_desc: "Испытайте комфорт на самом высоком уровне с нашими опытными водителями.",
        veh_2_badge: "VIP МИКРОАВТОБУС",
        veh_2_title: "VIP SPRINTER",
        veh_2_desc: "Идеальное решение для больших групп, оборудованный и роскошный автомобиль.",
        veh_3_badge: "MAYBACH",
        veh_3_title: "MAYBACH VITO",
        veh_3_desc: "Уникальный автомобиль с VIP-дизайном для ваших особых гостей.",

        veh_page_title: "НАШ РОСКОШНЫЙ АВТОПАРК",
        veh_page_h1: "Наши VIP Автомобили",
        veh_page_sub: "ДЛЯ ВАШЕГО КОМФОРТА",
        veh_page_h2: "Наш Большой и Современный Автопарк",
        veh1_tag: "МАРКА MERCEDES",
        veh1_title: "MERCEDES VITO VIP (6+1)",
        veh1_desc: "Самый комфортный вариант для вашей семьи или компании друзей во время отпуска на Кипре. Почувствуйте престиж благодаря большой вместимости багажа и кожаным сиденьям.",
        veh1_spec_pax: "6+1 Чел.",
        veh1_spec_lug: "5 Багаж",
        veh1_spec_ac: "Кондиционер",
        veh2_tag: "МАРКА MERCEDES",
        veh2_title: "MERCEDES SPRINTER VIP (15+1)",
        veh2_desc: "Наш VIP-микроавтобус с высоким потолком и телевизором, идеально подходящий для больших групп, свадебных торжеств и казино-туров.",
        veh2_spec_pax: "15+1 Чел.",
        veh2_spec_lug: "15 Багаж",
        veh2_spec_tv: "Развлечения",
        tab_rez: "СДЕЛАТЬ БРОНЬ",
        tab_gal: "ФОТОГРАФИИ АВТО",
        tab_com: "ОТЗЫВЫ КЛИЕНТОВ",
        pl_name: "Имя Фамилия",
        pl_phone: "Телефон",
        btn_offer: "ПОЛУЧИТЬ ЦЕНУ",
        com1_text: "\"Машина была очень чистой, водитель встретил нас у дверей. Спасибо.\" - Ахмет Й.",
        com2_text: "\"Наша группа осталась очень довольна, угощения в машине были прекрасны.\" - Мехмет К.",

        about_page_title: "VIP CYPRUS TRAVEL",
        about_page_h1: "О Нас",
        about_sub: "КТО МЫ?",
        about_h2: "Мы Превращаем Путешествие в Искусство на Кипре",
        about_p1: "Как <strong>VIP CYPRUS TRAVEL</strong>, мы уже много лет играем ведущую роль в секторе туризма, транспорта и VIP-трансферов в Турецкой Республике Северного Кипра (ТРСК). Наша цель - предложить вам не просто услугу трансфера, а престижный образ жизни с первого момента вашего пребывания на острове.",
        about_p2: "Благодаря нашим трансферам из аэропорта Эрджан и частным турам мы предлагаем широкий спектр услуг от индивидуальных гостей до руководителей корпоративных компаний. Мы предоставляем бесперебойное круглосуточное обслуживание с нашими роскошными автомобилями Mercedes в нашем автопарке и нашей командой экспертов.",
        about_miss_title: "Наша Миссия",
        about_miss_desc: "Предоставлять услуги, ориентированные на удовлетворение потребностей гостей, которые меняют ситуацию в транспортном секторе, ставя во главу угла безопасность и качество.",
        about_vis_title: "Наше Видение",
        about_vis_desc: "Быть первым, самым инновационным и самым надежным VIP-брендом, который приходит на ум в секторе туризма и трансферов Северного Кипра.",
        about_cert_title: "Официально Утвержденное Агентство",
        about_cert_desc: "Наша компания является профессиональным туристическим агентством, авторизованным TÜRSAB и Министерством туризма ТРСК.",
        about_cert_btn: "ПРОВЕРИТЬ САЙТ",
        about_help_title: "Нужна помощь?",
        about_help_desc: "Наша операционная команда 24/7 готова ответить на ваши вопросы.",
        about_help_btn: "Позвонить Сейчас",
        about_trust_tag: "ДОВЕРИЕ И КАЧЕСТВО",
        about_trust_title: "Мы Подтверждаем Наше Качество",
        about_trust_desc: "Все наши автомобили имеют сертификаты пассажирских перевозок и соответствуют высоким стандартам безопасности ТРСК.",
        about_exp_year: "Лет Опыта",

        // --- SERVICES PAGE ---
        srv_page_tag: "VIP ПРИВИЛЕГИЯ",
        srv_page_title: "Мы Не Знаем Границ в Наших Услугах",
        srv_page_1_badge: "VIP ТРАНСФЕР",
        srv_page_1_title: "VIP-Трансфер из Аэропорта Эрджан",
        srv_page_1_p1: "Почувствуйте себя особенным с первого момента пребывания на Кипре. Мы бесперебойно и с комфортом доставим вас из аэропорта Эрджан в ваш отель в регионах Кирения, Никосия, Фамагуста или Бафра на наших роскошных автомобилях Mercedes Vito.",
        srv_page_1_p2: "Вы можете безопасно путешествовать, сделав предварительное бронирование в любое время суток (24/7), не беспокоясь о задержках рейсов. Ваш водитель встретит вас по имени.",
        srv_page_1_btn: "УЗНАТЬ ЦЕНУ",
        srv_page_2_badge: "ЧАСТНАЯ АРЕНДА",
        srv_page_2_title: "Аренда Авто с Водителем",
        srv_page_2_p1: "Мы предлагаем профессиональные услуги по аренде VIP-автомобилей с водителем для ваших деловых встреч, частных приглашений или поездок по острову на весь день. Просто задайте маршрут, а остальное оставьте нам.",
        srv_page_2_p2: "Пусть наш водитель ждет вас там, где вы пожелаете, в наших полностью оборудованных автомобилях с Wi-Fi и угощениями. Управление временем полностью в ваших руках.",
        srv_page_2_btn: "ДЕТАЛИ",
        srv_page_3_badge: "ВСТРЕЧА И ПРИВЕТСТВИЕ",
        srv_page_3_title: "VIP Встреча и Сопровождение",
        srv_page_3_p1: "Мы от вашего имени встретим ваших особых гостей или представителей компании самым престижным образом. Мы встречаем со специальными табличками с именами или логотипами компаний и помогаем с багажом.",
        srv_page_3_p2: "Мы знаем, как важно первое впечатление. Мы проводим безупречную операцию, которая заставит ваших гостей почувствовать себя особенными.",
        srv_page_3_btn: "БРОНИРОВАНИЕ",
        // --- TOURS PAGE ---
        tour_page_tag: "ОТКРОЙТЕ ДЛЯ СЕБЯ КИПР",
        tour_page_h1: "Частные Туры по Кипру",
        tour_page_p: "Откройте для себя тысячелетнюю историю острова с комфортом на наших роскошных автомобилях.",
        tour_page_sub: "ПОПУЛЯРНЫЕ МАРШРУТЫ",
        tour_page_h2: "Туры по Культуре и Природе Кипра",

        t1_badge: "VIP Тур",
        t1_tag: "Регион Кирения",
        t1_title: "Кирения и Беллапаис",
        t1_desc: "Очаровательная атмосфера гавани и уникальная архитектура аббатства Беллапаис.",
        t1_l1: "Киренийский замок",
        t1_l2: "Старая пристань",
        t1_l3: "Аббатство Беллапаис",

        t2_badge: "Самый Популярный",
        t2_tag: "Регион Фамагуста",
        t2_title: "Фамагуста и Вароша",
        t2_desc: "Станьте свидетелем древних руин Саламина и загадочной истории закрытой Вароши.",
        t2_l1: "Древний город Саламин",
        t2_l2: "Мечеть Лала Мустафа Паша",
        t2_l3: "Закрытая Вароша",

        t3_badge: "Столица",
        t3_tag: "Столица",
        t3_title: "Культура Никосии",
        t3_desc: "Пройдите по османским и лузиньянским следам в единственной в мире разделенной столице.",
        t3_l1: "Бюйюк-Хан",
        t3_l2: "Мечеть Селимие",
        t3_l3: "Базар Араста",

        t4_badge: "Природа",
        t4_tag: "Регион Карпаз",
        t4_title: "Карпаз и Золотой Пляж",
        t4_desc: "Самая девственная природа острова, свободные ослы и великолепный Золотой пляж.",
        t4_l1: "Апостолос Андреас",
        t4_l2: "Золотой Пляж",
        t4_l3: "Деревня Дипкарпаз",

        tab_places: "МЕСТА",
        tab_gallery: "ГАЛЕРЕЯ",
        btn_tour_offer: "ПОЛУЧИТЬ ЦЕНУ",
        // --- CONTACT PAGE ---
        contact_page_tag: "СВЯЖИТЕСЬ С НАМИ",
        contact_page_h1: "Контакты",
        contact_page_p: "Вы можете связаться с нами 24/7 по вопросам, запросам на бронирование и частным турам.",

        contact_address_title: "Наш Адрес",
        contact_address_desc: "Район Гавани Кирении, №:45 <br> Кирения / ТРСК",
        contact_phone_title: "Телефон и WhatsApp",
        contact_email_title: "Эл. почта",

        contact_form_title: "Отправить Сообщение",
        contact_label_name: "Имя Фамилия",
        contact_ph_name: "напр., Иван Иванов",
        contact_label_phone: "Номер Телефона",
        contact_ph_phone: "+90 5XX XXX XX XX",
        contact_label_email: "Эл. адрес",
        contact_ph_email: "example@mail.com",
        contact_label_subject: "Тема",
        contact_opt_1: "Бронирование Трансфера",
        contact_opt_2: "Информация о Туре",
        contact_opt_3: "Жалоба / Предложение",
        contact_opt_4: "Другое",
        contact_label_message: "Ваше Сообщение",
        contact_ph_message: "Чем мы можем вам помочь?",
        contact_btn_send: "ОТПРАВИТЬ",
        //WP MESSAGE
        wp_msg_default: "Здравствуйте, я хотел бы получить информацию о ваших услугах VIP-трансфера.",
        wp_msg_srv1: "Здравствуйте, могу ли я получить информацию об услуге трансфера в отель?",
        wp_msg_srv2: "Здравствуйте, могу ли я получить информацию об аренде автомобиля с водителем?",
        wp_msg_srv3: "Здравствуйте, могу ли я получить информацию о вашей услуге VIP-встречи?",
        wp_msg_tour_girne: "Здравствуйте, я хотел бы получить информацию и цены на тур Кирения и Беллапаис.",
        wp_msg_tour_magosa: "Здравствуйте, я хотел бы получить информацию и цены на тур Фамагуста и Вароша.",
    }
};